#!/bin/bash

# Optimizes compression of PNG files
# Run `sudo apt install trimage` first.
git diff --name-only --cached | grep -iE '^.*\.(png|jpg|jpeg)$' | while read -r line
do
  trimage -f "$line"
  git add "$line"
done
